project_id = "glovzlprnldohvxiwmjf"

[functions.battery-optimizer]
verify_jwt = false

[functions.test-battery-api]
verify_jwt = false

[functions.check-optimization-logs]
verify_jwt = false

[functions.download-optimization-report]
verify_jwt = false