// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glovzlprnldohvxiwmjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsb3Z6bHBybmxkb2h2eGl3bWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDU3ODQsImV4cCI6MjA3MzY4MTc4NH0.wnud9NL27cD1gLcA0h979aepHD6pB_g9xgyiWoGS_ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});